### ISSUE TITLE
如何在云服务器上开启雷电需要的vt技术？

### ISSUE THREAD

**Issue by JuniorHighSchoolStudent** [wukan1986/thsauto#2]
请教大佬如何在腾讯云服务器上开启雷电需要的vt技术？

**Comment by wukan1986** [comment]
https://cloud.tencent.com/document/product/213/15379

> CVM 实例的使用限制
> 暂不支持虚拟化软件安装和再进行虚拟化（如安装使用 VMware 或者 Hyper-V）。

建议问客服。
也许有些机型支持虚拟化，或者其它云厂商的部分机型支持虚拟化

**Comment by JuniorHighSchoolStudent** [comment]
谢谢大佬的回复，正在询问腾讯云的客服。

**Comment by JuniorHighSchoolStudent** [comment]
> https://cloud.tencent.com/document/product/213/15379
> 
> > CVM 实例的使用限制
> > 暂不支持虚拟化软件安装和再进行虚拟化（如安装使用 VMware 或者 Hyper-V）。
> 
> 建议问客服。 也许有些机型支持虚拟化，或者其它云厂商的部分机型支持虚拟化

大佬用的哪家的云 还是自己本地部署的？

**Comment by wukan1986** [comment]
我自己是在本地用的

雷电模拟器弹出：检测到没有开启VT界面时，马上开启时
不要点击`马上开启`，按`ESC`可跳过此步

你可以试试，或找找其它支持不开VT的模拟器

**Comment by wukan1986** [comment]
https://www.bilibili.com/read/cv23624556/?from=search&spm_id_from=333.337.0.0

此文说Azure可以开启嵌套虚拟化，你可以找客服确认一下

阿里云客服说的神龙服务器可以二次虚拟化，但价格非常贵

**Comment by JuniorHighSchoolStudent** [comment]
谢谢大佬的回复。客服回复的是他们有裸金属服务器支持二次虚拟化。

**Comment by JuniorHighSchoolStudent** [comment]
> https://www.bilibili.com/read/cv23624556/?from=search&spm_id_from=333.337.0.0
> 
> 此文说Azure可以开启嵌套虚拟化，你可以找客服确认一下
> 
> 阿里云客服说的神龙服务器可以二次虚拟化，但价格非常贵

阿里的太坑，而且太贵。之前就是用的他们家。
