### ISSUE TITLE
卖出报错

### ISSUE THREAD

**Issue by xblcity** [wukan1986/thsauto#4]
ERROR    | src.ths:single_sell:123 - 卖出 xxx 时发生错误: -32001 Jsonrpc error: <androidx.test.uiautomator.UiObjectNotFoundException> data: UiSelector[CHILD=UiSelector[CLASS=android.widget.EditText], RESOURCE_ID=com.hexin.plat.android:id/dialogplus_view_container], method: setText
 电脑分辨率 1560* 1600，雷电分辨率设置为 360 * 1500 、DPI 180

**Comment by wukan1986** [comment]
https://github.com/wukan1986/thsauto/blob/main/thsauto/base.py#L380

对象没有找到

你可以试着在这之前加一些延时语句，等待弹出股票输入界面

**Comment by xblcity** [comment]
node = d(resourceId="com.hexin.plat.android:id/dialogplus_view_container").child(className='android.widget.EditText')
是这个 node 没有弹出导致 x.set_text(node, stockcode) 报错是吗
node.wait(exists=True, timeout=2.0) 这里的 timeout 是指 2s 后执行，还是最多等待 2s
我如果想不报错，是不是改这里的 timeout，改到非常大可以解决？

**Comment by xblcity** [comment]
代码里有关于 auto_stockcode 的注释，这里如果 auto_stockcode 没有的话，后面的执行也就没意义了，这里直接阻塞了
看到代码已经加了最多 1.5s 的延迟，但还是会有异常发生
这里是不是可以通过：
1.设置 auto_stockcode 默认值（在固定分辨率情况下）2.或者通过其他方式获取坐标，3.或者重新加载下单页面 尝试解决
猜测这个错误复现需要长时间不操作再触发下单函数，不容易复现。
当我触发调仓操作，出错的是卖的操作，后面买的操作没有出错（所以想着 auto_stockcode 没有的话是不是可以尝试重新加载下单页面）

**Comment by wukan1986** [comment]
1. 固定分辨率下的默认值不推荐，因为不灵活
2. 暂时不知道
3. 是否在最外层套一个try expect，收到UiObjectNotFoundException就重试最多两次，可以考虑用tenacity

注意：但如果弹出的对话框没有关闭，后面就会无法点击
