### ISSUE TITLE
get_positions 获取最新的仓位有误

### ISSUE THREAD

**Issue by xblcity** [wukan1986/thsauto#5]
在其他终端操作后，模拟器端调用 get_positions 获取最新的仓位有误，是之前的数据，非最新
发现点刷新按钮后可以获取最新的持仓信息，请问有暴露右上角刷新按钮的方法吗

**Comment by wukan1986** [comment]
不好意思，过了4天才看到。

已经添加了刷新功能。使用方法为`t.refresh()`
