### ISSUE TITLE
长时间不操作， 脚本再次触发同花顺操作 uiautomator-v2 会先重启

### ISSUE THREAD

**Issue by xblcity** [wukan1986/thsauto#7]
上午启动，下午触发同花顺操作的时候，触发操作之前，uiautomator-v2 又进行了重启（类似于第一次初始化时的启动），重启大概会再花 20s 的时间，有解决方案可以避免重启吗

[D 240624 14:49:25 __init__:661] [pid:24656] [emulator-5554] kill process(ps): uiautomator
[D 240624 14:49:25 __init__:682] [pid:24656] [emulator-5554] uiautomator-v2 is starting ... left: 40.0s

**Comment by wukan1986** [comment]
长时间不用，可能被杀后台了。
1. 是否考虑每隔一定时间调用`t.refresh()`,
2. 或者在要正试操作前三分钟做一下查资金等操作
