### ISSUE TITLE
空仓调用 get_balance 取值结果不正确

### ISSUE THREAD

**Issue by xblcity** [wukan1986/thsauto#8]
期望结果：持仓市值为 0，可用资金 满值。
实际：持仓市值 满值，可用资金 为 0

**Comment by wukan1986** [comment]
我同花顺版本为 Version 10.90.02，检查了一下并没有错误

https://github.com/wukan1986/thsauto/blob/main/thsauto/base.py#L61

`names = ['总资产', '浮动盈亏', '当日参考盈亏', '当日参考盈亏率', '持仓市值', '可用资金', '可取资金']`

这里的位置你可以按实际情况进行调整

**Comment by xblcity** [comment]
客户端是 10.93.02，信息板块应该是一样的
信息板块依次是 总资产 浮动盈亏 当日参考盈亏 总市值 可用 可取

1.代码里的 names 是根据什么 key 获取的，是页面上展示的中文名称吗
2.为什么代码里的 names 一共返回了7个，而不是6个
3.由于已经空仓了，持仓是没有的，当日盈亏和可取都是 --，获取不到正确值是和这个有关系吗
4.任意买入一个仓位，get_position 的取值就是正常的

**Comment by wukan1986** [comment]
取第2、4两行的字符串。然后与自己定义的名字进行组装。

由于第2行的`当日参考盈亏`有两个数字，所以返回7

![微信图片_20240627121228](https://github.com/wukan1986/thsauto/assets/1826707/be44ef4c-0e8e-4c7c-9304-bebded7ba665)
