### ISSUE TITLE
撤销委托报错

### ISSUE THREAD

**Issue by xblcity** [wukan1986/thsauto#9]
先调用了 get_orders(break_after_done=True)
然后调用了 cancel_single(self.t.order_at(0))
然后就出现报错： list index out of range
页面卡在这里了
![image](https://github.com/user-attachments/assets/a5d182ac-2596-4345-ba62-a5c9fdfca8dd)
同花顺版本 10.93.02

**Comment by mafulong** [comment]
https://github.com/wukan1986/thsauto/issues/10

你试下我这个修复呢，看起来ui和我手机一样，小米14pro + 同花顺最新版。

**Comment by xblcity** [comment]
> #10
> 
> 你试下我这个修复呢，看起来ui和我手机一样，小米14pro + 同花顺最新版。

最近没有再用这个了，用迅投QMT会比较稳定
